const stories=[
['WORLD','A new map of possibility is taking shape across the world’s cities','Communities are building practical answers to shared challenges.','Mara Okafor','assets/lead-city.png'],
['TECHNOLOGY','Open tools are giving small teams a bigger voice','Builders are choosing shared infrastructure over closed ecosystems.','Ibrahim Khan','assets/tech-lab.png'],
['ENVIRONMENT','The restoration projects proving nature can rebound','A closer look at patient work with a measurable impact.','Sofia Alvarez','assets/climate-coast.png'],
['BUSINESS','The patient capital behind a more useful economy','Founders and funders are rethinking what growth should mean.','Daniel Reyes','assets/lead-city.png'],
['HEALTH','The neighborhood clinics changing preventative care','A new model puts trust before treatment.','Amara Bello','assets/climate-coast.png'],
['CULTURE','The artists making room for a slower internet','Their work asks us to look, listen and stay a little longer.','Nadia Rahman','assets/tech-lab.png']
];
const grid=document.getElementById('latestGrid');let count=3;
function renderStories(){grid.innerHTML=stories.slice(0,count).map(s=>`<article class="latest-card"><img src="${s[4]}" alt="Original editorial illustration for ${s[1]}"><div class="kicker">${s[0]}</div><h3><a href="#article">${s[1]}</a></h3><p>${s[2]}</p><div class="byline">${s[3]} · 6 min · 2h ago</div></article>`).join('');document.getElementById('loadMore').style.display=count>=stories.length?'none':'block'}
renderStories();document.getElementById('loadMore').onclick=()=>{count=Math.min(count+3,stories.length);renderStories()};
document.getElementById('menuToggle').onclick=()=>{document.getElementById('mainNav').classList.toggle('open')};
document.getElementById('searchToggle').onclick=()=>{const el=document.getElementById('searchbar');el.classList.toggle('open');if(el.classList.contains('open'))document.getElementById('searchInput').focus()};document.getElementById('closeSearch').onclick=()=>document.getElementById('searchbar').classList.remove('open');
document.getElementById('searchInput').oninput=e=>{const q=e.target.value.toLowerCase();const matches=stories.filter(s=>s.join(' ').toLowerCase().includes(q));document.getElementById('searchResults').innerHTML=q?`<div class="search-results">${matches.map(s=>`<a href="#latest"><b>${s[0]}</b> ${s[1]}</a>`).join('')||'<span>No stories found</span>'}</div>`:''};
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');if(btn.dataset.tab==='popular'){const old=stories.slice();stories.sort((a,b)=>a[1].length-b[1].length);renderStories();stories.splice(0,stories.length,...old)}else renderStories()});
document.getElementById('newsletterForm').onsubmit=e=>{e.preventDefault();document.getElementById('newsletterMessage').textContent='You’re on the list. Welcome to the Daily Brief.';e.target.reset()};document.getElementById('playAudio').onclick=e=>{e.target.textContent=e.target.textContent.includes('Play')?'Ⅱ Pause 18:42':'▶ Play 18:42'};
window.addEventListener('scroll',()=>{const h=document.documentElement;document.getElementById('progress').style.width=`${(h.scrollTop/(h.scrollHeight-h.clientHeight))*100}%`});document.getElementById('editionBtn').onclick=()=>{const editions=['International','Pakistan','Asia','Europe','Middle East','Americas'];const current=localStorage.getItem('wp-edition')||'International';const next=editions[(editions.indexOf(current)+1)%editions.length];localStorage.setItem('wp-edition',next);document.getElementById('editionBtn').textContent=next+' ▾'};if(localStorage.getItem('wp-edition'))document.getElementById('editionBtn').textContent=localStorage.getItem('wp-edition')+' ▾';
